/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * blog
 * Blog API
 * OpenAPI spec version: 0.1.0
 */
export interface ArticleRequest {
  content: string;
  description: string;
  title: string;
}

export interface ArticleResponse {
  author: string;
  content: string;
  created_at: string;
  description: string;
  id: string;
  status: string;
  title: string;
  updated_at: string;
}

export type ListingArticleResponseItemsItem = {
  author: string;
  content: string;
  created_at: string;
  description: string;
  id: string;
  status: string;
  title: string;
  updated_at: string;
};

export interface ListingArticleResponse {
  items: ListingArticleResponseItemsItem[];
  pages: number;
}

export interface User {
  avatar_url: string;
  /** @minimum 0 */
  id: number;
  login: string;
  name: string;
}

export type ListArticlesParams = {
/**
 * Filter by status
 */
status?: string;
/**
 * Page number
 */
page?: number;
};

